language: python
python:
    - '3.6'
services:
    - docker
before_install:
    - docker-compose up -d
    
install:
    - docker build -t 
    - pip install -r requirements.txt
script:
    - pytest pytest.py