version: '3'
services:
        web_server:
                build:
                        context: ./web_server/
                container_name: web_server
                ports:
                        - "80:80"
