version: '3'
services:
        web_server:
                build:
                        context: ./web_server/
                container_name: web_server
                ports:
                        - "80:80"

        database_server:
                image: mysql
                command: --default-authentication-plugin=mysql_native_password
                restart: always
                volumes:
                        - ./database_server/data:/var/lib/mysql
                        - ./database_server/scripts:/docker-entrypoint-initdb.d/
                ports:
                        - "3306:3306"
                        - "33060:33060"
                environment:
                        MYSQL_ROOT_PASSWORD: pass
