CREATE DATABASE Garbage;

USE Garbage;

CREATE TABLE User(
	ID INT(10) NOT NULL AUTO_INCREMENT,
	User_Name VARCHAR(50) NOT NULL UNIQUE,
	Password VARCHAR(255) NOT NULL,
	Created DATETIME DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(ID)
);

CREATE TABLE Post(
	Post_Number INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	Poster INT(10),
	Post_Time DATETIME DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY(Poster) REFERENCES User(ID),
	PRIMARY KEY(Post_Number)
);


